const SHOP_DATA = [
  {
    title: 'Hats',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        price: 25,
        rating: 4.5,
        reviewCount: 128,
        reviews: [
          {
            user: 'John D.',
            rating: 5,
            comment: 'Perfect fit and great quality!',
          },
          {
            user: 'Sarah M.',
            rating: 4,
            comment: 'Love the color, very stylish.',
          },
          {
            user: 'Mike R.',
            rating: 5,
            comment: 'Best hat I have ever owned.',
          },
        ],
      },
      {
        id: 2,
        name: 'Blue Beanie',
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        price: 18,
        rating: 4.2,
        reviewCount: 95,
        reviews: [
          {
            user: 'Emily K.',
            rating: 4,
            comment: 'Warm and comfortable for winter.',
          },
          {
            user: 'David L.',
            rating: 5,
            comment: 'Great beanie, highly recommend!',
          },
          { user: 'Anna P.', rating: 4, comment: 'Nice quality material.' },
        ],
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        price: 35,
        rating: 4.8,
        reviewCount: 76,
        reviews: [
          { user: 'Chris T.', rating: 5, comment: 'Authentic cowboy look!' },
          { user: 'Jessica H.', rating: 5, comment: 'Perfect for festivals.' },
          { user: 'Tom B.', rating: 4, comment: 'Good quality leather.' },
        ],
      },
      {
        id: 4,
        name: 'Grey Brim',
        imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
        price: 25,
        rating: 4.3,
        reviewCount: 112,
        reviews: [
          { user: 'Lisa W.', rating: 4, comment: 'Goes with everything!' },
          { user: 'Kevin S.', rating: 5, comment: 'Sleek and modern design.' },
          { user: 'Rachel G.', rating: 4, comment: 'Very versatile hat.' },
        ],
      },
      {
        id: 5,
        name: 'Green Beanie',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        price: 18,
        rating: 4.1,
        reviewCount: 89,
        reviews: [
          { user: 'Mark J.', rating: 4, comment: 'Love the green color.' },
          { user: 'Sophie N.', rating: 4, comment: 'Keeps my head warm.' },
          { user: 'Alex C.', rating: 5, comment: 'Great value for money.' },
        ],
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        price: 14,
        rating: 4.6,
        reviewCount: 156,
        reviews: [
          { user: 'Brian F.', rating: 5, comment: 'Perfect summer cap!' },
          { user: 'Megan L.', rating: 4, comment: 'Fun design, love it.' },
          { user: 'Steve H.', rating: 5, comment: 'Great for beach days.' },
        ],
      },
      {
        id: 7,
        name: 'Red Beanie',
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        price: 18,
        rating: 4.4,
        reviewCount: 103,
        reviews: [
          { user: 'Emma R.', rating: 5, comment: 'Vibrant red color!' },
          { user: 'Daniel M.', rating: 4, comment: 'Soft and cozy.' },
          {
            user: 'Olivia K.',
            rating: 4,
            comment: 'Perfect for cold weather.',
          },
        ],
      },
      {
        id: 8,
        name: 'Wolf Cap',
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        price: 14,
        rating: 4.7,
        reviewCount: 134,
        reviews: [
          { user: 'Ryan T.', rating: 5, comment: 'Cool wolf design!' },
          { user: 'Ashley B.', rating: 5, comment: 'My son loves it.' },
          { user: 'Jason P.', rating: 4, comment: 'Unique and stylish.' },
        ],
      },
      {
        id: 9,
        name: 'Blue Snapback',
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        price: 16,
        rating: 4.5,
        reviewCount: 147,
        reviews: [
          { user: 'Tyler S.', rating: 5, comment: 'Perfect snapback fit!' },
          { user: 'Nicole D.', rating: 4, comment: 'Great everyday cap.' },
          { user: 'Brandon W.', rating: 5, comment: 'Love the blue color.' },
        ],
      },
    ],
  },
  {
    title: 'Sneakers',
    items: [
      {
        id: 10,
        name: 'Adidas NMD',
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        price: 220,
        rating: 4.9,
        reviewCount: 312,
        reviews: [
          {
            user: 'James L.',
            rating: 5,
            comment: 'Most comfortable sneakers ever!',
          },
          { user: 'Amanda C.', rating: 5, comment: 'Worth every penny.' },
          {
            user: 'Robert K.',
            rating: 5,
            comment: 'Amazing quality and style.',
          },
        ],
      },
      {
        id: 11,
        name: 'Adidas Yeezy',
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        price: 280,
        rating: 4.8,
        reviewCount: 278,
        reviews: [
          {
            user: 'Michael B.',
            rating: 5,
            comment: 'Iconic design, love them!',
          },
          {
            user: 'Jennifer S.',
            rating: 5,
            comment: 'Super comfortable and stylish.',
          },
          { user: 'William T.', rating: 4, comment: 'Great for casual wear.' },
        ],
      },
      {
        id: 12,
        name: 'Black Converse',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        price: 110,
        rating: 4.6,
        reviewCount: 423,
        reviews: [
          {
            user: 'Sarah J.',
            rating: 5,
            comment: 'Classic style never goes out!',
          },
          { user: 'David R.', rating: 4, comment: 'Comfortable and timeless.' },
          {
            user: 'Laura M.',
            rating: 5,
            comment: 'Perfect everyday sneakers.',
          },
        ],
      },
      {
        id: 13,
        name: 'Nike White AirForce',
        imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        price: 160,
        rating: 4.7,
        reviewCount: 356,
        reviews: [
          {
            user: 'Chris P.',
            rating: 5,
            comment: 'Clean white design, love it!',
          },
          { user: 'Michelle H.', rating: 5, comment: 'Goes with any outfit.' },
          { user: 'Andrew F.', rating: 4, comment: 'Classic Nike quality.' },
        ],
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
        price: 160,
        rating: 4.5,
        reviewCount: 198,
        reviews: [
          {
            user: 'Kevin G.',
            rating: 5,
            comment: 'Bold red color stands out!',
          },
          {
            user: 'Stephanie L.',
            rating: 4,
            comment: 'Very comfortable high tops.',
          },
          { user: 'Eric W.', rating: 5, comment: 'Great for basketball.' },
        ],
      },
      {
        id: 15,
        name: 'Nike Brown High Tops',
        imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        price: 160,
        rating: 4.4,
        reviewCount: 167,
        reviews: [
          { user: 'Nathan R.', rating: 4, comment: 'Unique brown color!' },
          {
            user: 'Danielle K.',
            rating: 5,
            comment: 'Very stylish and comfy.',
          },
          { user: 'Matthew S.', rating: 4, comment: 'Good quality materials.' },
        ],
      },
      {
        id: 16,
        name: 'Air Jordan Limited',
        imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        price: 190,
        rating: 4.9,
        reviewCount: 289,
        reviews: [
          {
            user: 'Jordan M.',
            rating: 5,
            comment: 'Absolute fire! Must have!',
          },
          {
            user: 'Taylor N.',
            rating: 5,
            comment: 'Limited edition, so cool!',
          },
          { user: 'Kyle B.', rating: 5, comment: 'Best Jordans I own.' },
        ],
      },
      {
        id: 17,
        name: 'Timberlands',
        imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        price: 200,
        rating: 4.7,
        reviewCount: 234,
        reviews: [
          {
            user: 'Marcus J.',
            rating: 5,
            comment: 'Durable and stylish boots!',
          },
          { user: 'Hannah P.', rating: 5, comment: 'Perfect for all seasons.' },
          {
            user: 'Derek T.',
            rating: 4,
            comment: 'Classic Timberland quality.',
          },
        ],
      },
    ],
  },
  {
    title: 'Jackets',
    items: [
      {
        id: 18,
        name: 'Black Jean Shearling',
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        price: 125,
        rating: 4.6,
        reviewCount: 89,
        reviews: [
          { user: 'Victoria L.', rating: 5, comment: 'So warm and stylish!' },
          { user: 'Patrick H.', rating: 4, comment: 'Great winter jacket.' },
          {
            user: 'Christina M.',
            rating: 5,
            comment: 'Love the shearling lining.',
          },
        ],
      },
      {
        id: 19,
        name: 'Blue Jean Jacket',
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        price: 90,
        rating: 4.5,
        reviewCount: 156,
        reviews: [
          { user: 'Rebecca S.', rating: 5, comment: 'Classic denim look!' },
          { user: 'Timothy D.', rating: 4, comment: 'Great fit and quality.' },
          { user: 'Monica R.', rating: 5, comment: 'Perfect for layering.' },
        ],
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        price: 90,
        rating: 4.3,
        reviewCount: 112,
        reviews: [
          { user: 'Gregory K.', rating: 4, comment: 'Nice grey wash color.' },
          { user: 'Samantha W.', rating: 5, comment: 'Goes with everything!' },
          { user: 'Justin F.', rating: 4, comment: 'Comfortable and trendy.' },
        ],
      },
      {
        id: 21,
        name: 'Brown Shearling',
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        price: 165,
        rating: 4.8,
        reviewCount: 78,
        reviews: [
          { user: 'Heather T.', rating: 5, comment: 'Luxurious and warm!' },
          { user: 'Douglas B.', rating: 5, comment: 'High quality shearling.' },
          { user: 'Kimberly N.', rating: 5, comment: 'Worth the investment.' },
        ],
      },
      {
        id: 22,
        name: 'Tan Trench',
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        price: 185,
        rating: 4.7,
        reviewCount: 94,
        reviews: [
          { user: 'Elizabeth C.', rating: 5, comment: 'Elegant trench coat!' },
          {
            user: 'Richard H.',
            rating: 5,
            comment: 'Perfect for fall weather.',
          },
          {
            user: 'Angela V.',
            rating: 4,
            comment: 'Classic and sophisticated.',
          },
        ],
      },
    ],
  },
  {
    title: 'Womens',
    items: [
      {
        id: 23,
        name: 'Blue Tanktop',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        price: 25,
        rating: 4.4,
        reviewCount: 187,
        reviews: [
          { user: 'Jessica R.', rating: 5, comment: 'Perfect summer top!' },
          { user: 'Melissa K.', rating: 4, comment: 'Comfortable and cute.' },
          { user: 'Lauren S.', rating: 4, comment: 'Great for workouts too.' },
        ],
      },
      {
        id: 24,
        name: 'Floral Blouse',
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        price: 20,
        rating: 4.6,
        reviewCount: 203,
        reviews: [
          {
            user: 'Natalie M.',
            rating: 5,
            comment: 'Beautiful floral pattern!',
          },
          { user: 'Diana L.', rating: 5, comment: 'Light and flowy fabric.' },
          { user: 'Brittany P.', rating: 4, comment: 'Great for spring.' },
        ],
      },
      {
        id: 25,
        name: 'Floral Dress',
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        price: 80,
        rating: 4.8,
        reviewCount: 176,
        reviews: [
          { user: 'Catherine H.', rating: 5, comment: 'Stunning dress!' },
          { user: 'Amanda T.', rating: 5, comment: 'Perfect for weddings.' },
          { user: 'Rachel B.', rating: 5, comment: 'So feminine and elegant.' },
        ],
      },
      {
        id: 26,
        name: 'Red Dots Dress',
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        price: 80,
        rating: 4.5,
        reviewCount: 145,
        reviews: [
          { user: 'Stephanie G.', rating: 5, comment: 'Love the polka dots!' },
          { user: 'Michelle W.', rating: 4, comment: 'Retro and stylish.' },
          { user: 'Ashley N.', rating: 5, comment: 'Great fit and quality.' },
        ],
      },
      {
        id: 27,
        name: 'Striped Sweater',
        imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        price: 45,
        rating: 4.3,
        reviewCount: 134,
        reviews: [
          { user: 'Vanessa D.', rating: 4, comment: 'Cozy and warm!' },
          { user: 'Tiffany J.', rating: 5, comment: 'Love the stripes.' },
          { user: 'Courtney F.', rating: 4, comment: 'Great for casual days.' },
        ],
      },
      {
        id: 28,
        name: 'Yellow Track Suit',
        imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        price: 135,
        rating: 4.7,
        reviewCount: 98,
        reviews: [
          { user: 'Kayla R.', rating: 5, comment: 'Bold yellow color!' },
          { user: 'Brooke S.', rating: 5, comment: 'Super comfortable.' },
          { user: 'Paige M.', rating: 4, comment: 'Great for lounging.' },
        ],
      },
      {
        id: 29,
        name: 'White Blouse',
        imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
        price: 20,
        rating: 4.4,
        reviewCount: 167,
        reviews: [
          { user: 'Allison K.', rating: 4, comment: 'Classic white blouse.' },
          { user: 'Megan H.', rating: 5, comment: 'Perfect for work.' },
          { user: 'Lindsay T.', rating: 4, comment: 'Good quality fabric.' },
        ],
      },
    ],
  },
  {
    title: 'Mens',
    items: [
      {
        id: 30,
        name: 'Camo Down Vest',
        imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        price: 325,
        rating: 4.6,
        reviewCount: 67,
        reviews: [
          { user: 'Brandon L.', rating: 5, comment: 'Premium quality vest!' },
          { user: 'Scott M.', rating: 5, comment: 'Love the camo pattern.' },
          { user: 'Trevor K.', rating: 4, comment: 'Very warm for winter.' },
        ],
      },
      {
        id: 31,
        name: 'Floral T-shirt',
        imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        price: 20,
        rating: 4.3,
        reviewCount: 143,
        reviews: [
          { user: 'Derek S.', rating: 4, comment: 'Cool summer shirt!' },
          { user: 'Austin R.', rating: 5, comment: 'Unique floral design.' },
          { user: 'Blake H.', rating: 4, comment: 'Comfortable fit.' },
        ],
      },
      {
        id: 32,
        name: 'Black & White Longsleeve',
        imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        price: 25,
        rating: 4.5,
        reviewCount: 189,
        reviews: [
          { user: 'Chad W.', rating: 5, comment: 'Classic black and white!' },
          { user: 'Dylan P.', rating: 4, comment: 'Great everyday shirt.' },
          { user: 'Evan T.', rating: 5, comment: 'Soft material.' },
        ],
      },
      {
        id: 33,
        name: 'Pink T-shirt',
        imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        price: 25,
        rating: 4.2,
        reviewCount: 156,
        reviews: [
          { user: 'Garrett N.', rating: 4, comment: 'Nice pink shade.' },
          { user: 'Hunter J.', rating: 5, comment: 'Comfortable and stylish.' },
          { user: 'Ian B.', rating: 4, comment: 'Good quality cotton.' },
        ],
      },
      {
        id: 34,
        name: 'Jean Long Sleeve',
        imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        price: 40,
        rating: 4.6,
        reviewCount: 123,
        reviews: [
          { user: 'Jake F.', rating: 5, comment: 'Love the denim look!' },
          { user: 'Logan C.', rating: 4, comment: 'Great for layering.' },
          { user: 'Mason D.', rating: 5, comment: 'Versatile shirt.' },
        ],
      },
      {
        id: 35,
        name: 'Burgundy T-shirt',
        imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        price: 25,
        rating: 4.4,
        reviewCount: 178,
        reviews: [
          { user: 'Noah G.', rating: 5, comment: 'Rich burgundy color!' },
          { user: 'Owen L.', rating: 4, comment: 'Great fit and feel.' },
          { user: 'Parker M.', rating: 4, comment: 'Perfect casual shirt.' },
        ],
      },
    ],
  },
];

export default SHOP_DATA;
